// Generated by CoffeeScript 1.7.1
var data;

data = [];

data.push({
  strokes: [[[0, 0], [80, 80]], [[80, 0], [0, 80]]],
  snappoints: [[10, 10], [80, 80], [80, 10], [10, 80]],
  type: 'path',
  attr: {
    d: "M10,10L80,80M80,10L10,80",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[0, 0], [0, 80]], [[0, 80], [80, 80]]],
  snappoints: [[10, 10], [10, 80], [80, 80]],
  type: 'path',
  attr: {
    d: "M10,10L10,80L80,80",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[0, 0], [80, 0]], [[0, 0], [80, 0]]],
  snappoints: [[10, 40], [80, 40]],
  type: 'path',
  attr: {
    d: "M10,40L80,40",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[10, 10], [10, 80]], [[10, 10], [10, 80]]],
  snappoints: [[40, 10], [40, 80]],
  type: 'path',
  attr: {
    d: "M40,10L40,80",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[10, 10], [10, 80]], [[10, 80], [80, 80]], [[80, 80], [80, 10]], [[80, 10], [10, 10]]],
  snappoints: [[10, 10], [10, 80], [80, 80], [80, 10]],
  type: 'path',
  attr: {
    d: "M10,10L10,80L80,80L80,10Z",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[10, 10], [10, 80]], [[10, 80], [160, 80]], [[160, 80], [160, 10]], [[160, 10], [10, 10]]],
  snappoints: [[10, 10], [10, 80], [160, 80], [160, 10]],
  type: 'path',
  attr: {
    d: "M10,10L10,80L160,80L160,10Z",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[10, 60], [40, 60]], [[40, 60], [40, 10]], [[40, 10], [70, 10]], [[70, 10], [70, 60]]],
  snappoints: [[10, 60], [40, 60], [40, 10], [70, 10], [70, 60]],
  type: 'path',
  attr: {
    d: "M10,60L40,60L40,10L70,10L70,60",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

data.push({
  strokes: [[[0, 0], [80, 80]], [[80, 0], [0, 80]]],
  snappoints: [[10, 25], [10, 55], [70, 40]],
  type: 'path',
  attr: {
    d: "M40,10a30,30,-90,0,1,0,60 M10,10L40,10M10,70L40,70M10,10L10,70",
    stroke: '#000000',
    fill: 'none',
    'stroke-width': 5
  }
});

console.log(JSON.stringify(data));
