// Generated by CoffeeScript 1.7.1
var a, f, s, x, y;

x = 10;

y = 20;

s = '#{x}, #{y}';

console.log(typeof s);

f = function(x, y) {
  return "" + x + ", " + y;
};

console.log(f(10, 20));

a = [
  10, 20, function(s) {
    return [s, s];
  }
];

console.log(JSON.stringify(a));
