// Generated by CoffeeScript 1.7.1
var a, x, y;

a = [[1, 10], [2, 20], [3, 30]];

x = a.map(function(e) {
  return e[0];
});

y = a.map(function(e) {
  return e[1];
});

console.log(Math.max.apply(Math, x));

console.log(Math.max.apply(Math, y));
