// Generated by CoffeeScript 1.7.1
window.kareobanaTemplate = {
  draw: function() {
    var drawpoints, p1, p2, p3, x, y, _i, _ref, _results;
    template.selectAll("*").remove();
    _results = [];
    for (x = _i = 0, _ref = drawWidth / 80; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
      _results.push((function() {
        var _j, _ref1, _results1;
        _results1 = [];
        for (y = _j = 0, _ref1 = drawHeight / 80; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          p2 = {
            x: x * 80,
            y: y * 80
          };
          p1 = {
            x: rand(drawWidth),
            y: rand(drawHeight)
          };
          while (dist(p1, p2) < 50 || dist(p1, p2) > 150) {
            p1 = {
              x: rand(drawWidth),
              y: rand(drawHeight)
            };
          }
          p3 = {
            x: rand(drawWidth),
            y: rand(drawHeight)
          };
          while (dist(p3, p2) < 50 || dist(p3, p2) > 150 || dist(p1, p3) < 50 || dist(p1, p3) > 150) {
            p3 = {
              x: rand(drawWidth),
              y: rand(drawHeight)
            };
          }
          drawpoints = [p1, p2, p3];
          _results1.push(template.append('path').attr({
            stroke: '#d0d0d0',
            'stroke-width': 3,
            fill: "none",
            d: line(drawpoints)
          }));
        }
        return _results1;
      })());
    }
    return _results;
  },
  change: function(deltax, deltay) {
    return this.draw();
  }
};
