// Generated by CoffeeScript 1.7.1
window.kareobanaTemplate2 = {
  draw: function() {
    var i, p1, p2, p3, _i, _results;
    template.selectAll("*").remove();
    _results = [];
    for (i = _i = 0; _i <= 40; i = ++_i) {
      p1 = {
        x: rand(drawWidth),
        y: rand(drawHeight)
      };
      p2 = {
        x: rand(drawWidth),
        y: rand(drawHeight)
      };
      while (dist(p1, p2) < 50 || dist(p1, p2) > 150) {
        p2 = {
          x: rand(drawWidth),
          y: rand(drawHeight)
        };
      }
      p3 = {
        x: rand(drawWidth),
        y: rand(drawHeight)
      };
      while (dist(p1, p3) < 50 || dist(p1, p3) > 150 || dist(p2, p3) < 50 || dist(p2, p3) > 150) {
        p3 = {
          x: rand(drawWidth),
          y: rand(drawHeight)
        };
      }
      _results.push(template.append('path').attr({
        stroke: '#d0d0d0',
        'stroke-width': 3,
        fill: "none",
        d: line([p1, p2, p3])
      }));
    }
    return _results;
  },
  change: function(deltax, deltay) {
    return this.draw();
  }
};
