// Generated by CoffeeScript 1.7.1
window.kareobanaTemplate4 = {
  draw: function() {
    var i, p1, p2, _i, _results;
    template.selectAll("*").remove();
    _results = [];
    for (i = _i = 0; _i <= 200; i = ++_i) {
      p1 = [rand(drawWidth), rand(drawHeight)];
      p2 = [rand(drawWidth), rand(drawHeight)];
      while (dist(p1, p2) < 20 || dist(p1, p2) > 30) {
        p2 = [rand(drawWidth), rand(drawHeight)];
      }
      _results.push(template.append('path').attr({
        stroke: '#d0d0d0',
        'stroke-width': 3,
        fill: "none",
        d: line([p1, p2])
      }));
    }
    return _results;
  },
  change: function(deltax, deltay) {
    return this.draw();
  }
};
