// Generated by CoffeeScript 1.7.1
var mt;

mt = null;

window.srand = function(n) {};

window.rand = function(n) {
  return Math.floor(Math.random() * n);
};

window.hypot = function(x, y) {
  return Math.sqrt(x * x + y * y);
};

window.dist = function(p1, p2) {
  return hypot(p1.x - p2.x, p1.y - p2.y);
};
