// Generated by CoffeeScript 1.7.1
window.meshTemplate = {
  params: {
    meshsize: 40,
    offset: {
      x: 0,
      y: 0
    }
  },
  draw: function() {
    var i, xsize, ysize, _i, _j, _ref, _ref1, _results;
    template.selectAll("*").remove();
    xsize = this.params.meshsize + this.params.offset.x;
    if (xsize > 1) {
      for (i = _i = 0, _ref = drawWidth / (this.params.meshsize + this.params.offset.x); 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        drawline(i * (this.params.meshsize + this.params.offset.x), 0, i * (this.params.meshsize + this.params.offset.x), drawHeight);
      }
    }
    ysize = this.params.meshsize + this.params.offset.y;
    if (ysize > 1) {
      _results = [];
      for (i = _j = 0, _ref1 = drawHeight / (this.params.meshsize + this.params.offset.y); 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
        _results.push(drawline(0, i * (this.params.meshsize + this.params.offset.y), drawWidth, i * (this.params.meshsize + this.params.offset.y)));
      }
      return _results;
    }
  },
  change: function(deltax, deltay) {
    this.params.offset.x = deltax;
    this.params.offset.y = deltay;
    return this.draw();
  }
};
