// Generated by CoffeeScript 1.7.1
var ipoint, splitstroke;

splitstroke = function(points) {
  var d, i, ind, p0, p1, pre, slow, splitstrokes;
  splitstrokes = [];
  pre = points[0];
  i = 0;
  ind = 0;
  slow = true;
  while (true) {
    p0 = ipoint(points, i * 100);
    p1 = ipoint(points, (i + 1) * 100);
    d = dist(p0, p1);
    if (d > 10) {
      slow = false;
    } else {
      if (d < 30 && !slow) {
        splitstrokes.push([pre, p0]);
        pre = p0;
        slow = true;
      }
    }
    if (p1[2] < 0) {
      break;
    }
    i += 1;
  }
  return splitstrokes;
};

ipoint = function(points, t) {
  var ind, p1, p2, plen, torig, x, y;
  torig = points[0][2];
  plen = points.length;
  if (t === 0 || plen === 1) {
    return [points[0][0], points[0][1], 0];
  }
  if (points[plen - 1][2] - torig < t) {
    return [points[plen - 1][0], points[plen - 1][1], -1];
  }
  ind = 0;
  while (true) {
    if (points[ind][2] - torig >= t) {
      break;
    }
    ind += 1;
  }
  p1 = points[ind - 1];
  p2 = points[ind];
  x = (p1[0] * ((p2[2] - torig) - t) + p2[0] * (t - (p1[2] - torig))) / (p2[2] - p1[2]);
  y = (p1[1] * ((p2[2] - torig) - t) + p2[1] * (t - (p1[2] - torig))) / (p2[2] - p1[2]);
  return [x, y, ind];
};
