// Generated by CoffeeScript 1.7.1
var flicker_key, flicker_secret;

flicker_key = "c0e778ffc1f3dd825fb3e665a2a7cc8c";

flicker_secret = "2d665c39c2ea3590";

window.flickr_search = function(keyword, callback) {
  var url;
  url = "https://api.flickr.com/services/rest?method=flickr.photos.search&per_page=10&text='" + keyword + "'&api_key=" + flicker_key + "&format=json";
  return $.ajax({
    url: url,
    dataType: "html",
    cache: false,
    success: function(data, textStatus) {
      var d, photos;
      data = data.replace(/^jsonFlickrApi\(/, '');
      data = data.replace(/\)$/, '');
      d = JSON.parse(data);
      photos = d['photos']['photo'];
      return callback(photos.map(function(photo) {
        return "http://farm" + photo['farm'] + ".staticflickr.com/" + photo['server'] + "/" + photo['id'] + "_" + photo['secret'] + ".jpg";
      }));
    },
    error: function(xhr, textStatus, errorThrown) {
      return alert("error " + textStatus);
    }
  });
};
